* Raspberry Pi Linux Tar SD Card Generator
** Why
Installing Linux from tar archives is cumbersome. 
Then also OSX does not support EXT filesystems. For that on OSX to flash an SD card for ArchLinuxARM, Alpine etc. a VM has to be started.
To make things easier the Docker image does exactly that. Makes it easy, fast and reproducible to generate and flash image to sd card on Mac and Linux.
** How
*** Mac OSX
#+BEGIN_SRC
docker run --rm --privileged
           -v $(pwd):/backup
           [-v SomeDistro.tar.gz:/app/distro.tar.gz]
           peelsky/rpi-sdcard-builder
           [PLATFORM=(rp2|rp3|oc1|oc2)]
           (copy|tar)
#+END_SRC

=(-v SomeDistro.tar.gz:/app/distro.tar.gz)= - use another distro tar archive (default: arch for rp2/rp3)
=[PLATFORM]= - sets image destitantion platform (default: rp3)
=(copy|tar)= - whether an img or tar.gz copy shall be created; mandatory when using =PLATFORM= parameter

**** Examples:
To get an `.img` for flashing on an SD card execute:
=docker run --rm --privileged -v $(pwd):/backup peelsky/rpi-sdcard-builder PLATFORM=rp3 copy=

To get an `.tgz` archive as a backup:
=docker run --rm --privileged -v $(pwd):/backup peelsky/rpi-sdcard-builder PLATFORM=rp3 tar=

To get an image of another distribution on an SD card, download the distro and execute:
=docker run --rm --privileged -v $(pwd):/backup -v {{PATH TO A TGZ}}:/app/distro.tar.gz peelsky/rpi-sdcard-builder PLATFORM={{PLATFORM_TYPE}} copy=
*** Linux
#+BEGIN_SRC
make TARGET=(...) [PLATFORM=(...)][DISTRO_TAR_URL=http://.../Archive.tar.gz] linux (copy|tar)
#+END_SRC

**** Examples:
To get an `.img` for flashing on an SD card execute:
=make PLATFORM=rp3 linux=

To get an `.tgz` archive as a backup:
=make PLATFORM=oc2 TARGET=$(pwd) linux tar=
** Flashing
/SIDE NOTE:/ To copy image onto an SD card execute from OSX:
=sudo dd bs=1m if=sdcard.img of={{DISK_ID}}=
